### ISSUE TITLE
Error when player Join

### ISSUE THREAD

**Issue by Ale1x** [GatitoUwU/DynamicPremium#3]
Hi, i get that error when a player joins the proxy after he did the /premium command

Including screenshot:

![image](https://user-images.githubusercontent.com/71466131/173598054-2ce595fb-7e11-42e5-9525-310c4651f9b5.png)

**Comment by GatitoUwU** [comment]
Lol! I've never seen this, sorry! :(

This is not a feature in DynamicPremium anymore, so it should not happen.
Again, sorry.
